// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76uJIqH_P9uCSElfA1sR16WKxzXMwJ8g',
    appId: '1:1055355766670:web:982ebce42b53b45b72c6df',
    messagingSenderId: '1055355766670',
    projectId: 'smartcart-9f249',
    authDomain: 'smartcart-9f249.firebaseapp.com',
    storageBucket: 'smartcart-9f249.firebasestorage.app',
    measurementId: 'G-YDCD9S0PW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFglkVpae171U9vFII8QZbbW6lO3Q2m8',
    appId: '1:1055355766670:android:18038c40eb0e4e5072c6df',
    messagingSenderId: '1055355766670',
    projectId: 'smartcart-9f249',
    storageBucket: 'smartcart-9f249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsDhjvtGr0Jf3CVW4C5CAuAycEubHCts',
    appId: '1:1055355766670:ios:761ded45680aeb1772c6df',
    messagingSenderId: '1055355766670',
    projectId: 'smartcart-9f249',
    storageBucket: 'smartcart-9f249.firebasestorage.app',
    androidClientId: '1055355766670-un10fkem4g6bidt09mqtvmtc3fhr6h19.apps.googleusercontent.com',
    iosClientId: '1055355766670-98hgk3e3qih424p51h1vnuadu4ddu279.apps.googleusercontent.com',
    iosBundleId: 'com.tonnom.smartcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsDhjvtGr0Jf3CVW4C5CAuAycEubHCts',
    appId: '1:1055355766670:ios:761ded45680aeb1772c6df',
    messagingSenderId: '1055355766670',
    projectId: 'smartcart-9f249',
    storageBucket: 'smartcart-9f249.firebasestorage.app',
    androidClientId: '1055355766670-un10fkem4g6bidt09mqtvmtc3fhr6h19.apps.googleusercontent.com',
    iosClientId: '1055355766670-98hgk3e3qih424p51h1vnuadu4ddu279.apps.googleusercontent.com',
    iosBundleId: 'com.tonnom.smartcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC76uJIqH_P9uCSElfA1sR16WKxzXMwJ8g',
    appId: '1:1055355766670:web:543ea7fb3c45e4d672c6df',
    messagingSenderId: '1055355766670',
    projectId: 'smartcart-9f249',
    authDomain: 'smartcart-9f249.firebaseapp.com',
    storageBucket: 'smartcart-9f249.firebasestorage.app',
    measurementId: 'G-LYFPJGSDYT',
  );
}
